main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('calc', views.calc, name='calc'),
    path('calc_p_profile', views.calc_p_profile, name='calc_p_profile'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration', views.user_reg, name='reg'),
    path('profile', views.profile, name='profile'),
    path('delete_fertilizer/<int:pk>', views.delete_fertilizer, name='delete_fertilizer'),
    path('add_fertilizer', views.add_fertilizer, name='add_fertilizer'),
    path('edit_fertilizer/<int:pk>', views.edit_fertilizer, name='edit_fertilizer'),
    path('profile_pp', views.profile_pp, name='profile_pp'),
    path('delete_p_profile/<int:pk>', views.delete_p_profile, name='delete_p_profile'),
    path('add_p_profile', views.add_p_profile, name='add_p_profile'),
    path('edit_p_profile/<int:pk>', views.edit_p_profile, name='edit_p_profile'),
    path('upload_p_profiles', views.upload_p_profiles, name='upload_p_profiles'),
    path('download_p_profiles', views.download_p_profiles, name='download_p_profiles'),
    path('upload_fertilizers', views.upload_fertilizers, name='upload_fertilizers'),
    path('download_fertilizers', views.download_fertilizers, name='download_fertilizers'),
    path('download_p_profiles_example', views.download_p_profiles_example, name='download_p_profiles_example'),
    path('download_fertilizers_example', views.download_fertilizers_example, name='download_fertilizers_example'),
]

npk_calc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Fertilizer(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    is_public = models.BooleanField(default=False)
    name = models.CharField('Название',max_length=100)
    nh4 = models.FloatField('% NH4', default=0)
    no3 = models.FloatField('% NO3', default=0)
    p2o5 = models.FloatField('% P2O5', default=0)
    k2o = models.FloatField('% K2O', default=0)
    cao = models.FloatField('% CaO', default=0)
    mgo = models.FloatField('% MgO', default=0)
    s = models.FloatField('% S', default=0)
    cl = models.FloatField('% Cl', default=0)
    fe = models.FloatField('% Fe', default=0)
    mn = models.FloatField('% Mn', default=0)
    b = models.FloatField('% B', default=0)
    zn = models.FloatField('% Zn', default=0)
    cu = models.FloatField('% Cu', default=0)
    mo = models.FloatField('% Mo', default=0)
    co = models.FloatField('% Co', default=0)
    si = models.FloatField('% Si', default=0)

    def __str__(self):
        return self.name
    
class P_profile(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, null=True, blank=True)
    is_public = models.BooleanField(default=False)
    name = models.CharField('Название',max_length=100)
    growth_stage = models.CharField(max_length=20, choices=[('start', 'Старт'), ('veg', 'Вегетация'), ('late_veg', 'Поздняя вегетация'), ('fruiting', 'Плодоношение')], default='start', verbose_name='Стадия роста')
    nh4 = models.FloatField('NH4, мг/л', default=0)
    no3 = models.FloatField('NO3, мг/л', default=0)
    p = models.FloatField('P, мг/л', default=0)
    k = models.FloatField('K, мг/л', default=0)
    ca = models.FloatField('Сa, мг/л', default=0)
    mg = models.FloatField('Mg, мг/л', default=0)
    s = models.FloatField('S, мг/л', default=0)
    cl = models.FloatField('Cl, мг/л', default=0)
    fe = models.FloatField('Fe, мкг/л', default=0)
    mn = models.FloatField('Mn, мкг/л', default=0)
    b = models.FloatField('B, мкг/л', default=0)
    zn = models.FloatField('Zn, мкг/л', default=0)
    cu = models.FloatField('Cu, мкг/л', default=0)
    mo = models.FloatField('Mo, мкг/л', default=0)
    co = models.FloatField('Co, мкг/л', default=0)
    si = models.FloatField('Si, мкг/л', default=0)

    def __str__(self):
        return self.name
    

main/forms.py
from django import forms
from .models import Fertilizer, P_profile

class FertilizerForm(forms.ModelForm):
    class Meta:
        model = Fertilizer
        fields = ['name', 'no3', 'nh4', 'p2o5', 'k2o', 'cao', 'mgo', 's', 'cl', 'fe', 'mn', 'b', 'zn', 'cu', 'mo', 'co', 'si']

class P_profileForm(forms.ModelForm):
    class Meta:
        model = P_profile
        fields = ['name', 'growth_stage', 'no3', 'nh4', 'p', 'k', 'ca', 'mg', 's', 'cl', 'fe', 'mn', 'b', 'zn', 'cu', 'mo', 'co', 'si']

class UploadFileForm(forms.Form):
    file = forms.FileField(label='')

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from .models import Fertilizer, P_profile
from django.db.models import Q
from .forms import FertilizerForm, P_profileForm, UploadFileForm
from scipy.optimize import minimize
import openpyxl
from django.http import HttpResponse, FileResponse
from django.conf import settings

# Create your views here.

def home(request):
    return render(request, 'main/home.html')

def download_p_profiles_example(request):
    return FileResponse((settings.MEDIA_ROOT / 'main' / 'p_profiles_example.xlsx').open('rb'), as_attachment=True)
def download_fertilizers_example(request):
    return FileResponse((settings.MEDIA_ROOT / 'main' / 'fertilizers_example.xlsx').open('rb'), as_attachment=True)

def user_login(request):
    er = {'error': None}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            er['error'] = "Неверный логин или пароль"
    return render(request, 'main/login.html', er)

def user_logout(request):
    logout(request)
    return redirect('home')

def user_reg(request):
    er = {'error': None}
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password != '' and username != '':
            if password == password2:
                if username and not User.objects.filter(username=username).exists():
                    user = User.objects.create_user(username=username, password=password)
                    login(request, user)
                    return redirect('home')
                else:
                    er['error'] = "Пользователь с таким логином уже существует"
            else:
                er['error'] = "Пароли не совпадают"
        else:
            er['error'] = "Введите логин и пароль"
    return render(request, 'main/reg.html', er)

def profile(request):
    if request.user.is_authenticated:
        fertilizers = Fertilizer.objects.filter(Q(user = request.user))
        return render(request, 'main/profile.html', {'fertilizers': fertilizers})
    else:
        return redirect('home')

def profile_pp(request):
    if request.user.is_authenticated:
        p_profile = P_profile.objects.filter(Q(user = request.user))
        return render(request, 'main/profile_pp.html', {'p_profiles': p_profile})
    else:
        return redirect('home')
    
def delete_fertilizer(request, pk):
    get_object_or_404(Fertilizer, pk=pk).delete()
    return redirect('profile')

def add_fertilizer(request):
    if request.method == 'POST':
        form = FertilizerForm(request.POST)
        if form.is_valid():
            fertilizer = form.save(commit=False)
            fertilizer.user = request.user
            fertilizer.save()
            return redirect('profile')
    else:
        form = FertilizerForm()
    return render(request, 'main/add_fertilizer.html', {'form': form})

def edit_fertilizer(request, pk):
    fertilizer = get_object_or_404(Fertilizer, pk=pk)
    if request.method == 'POST':
        form = FertilizerForm(request.POST, instance=fertilizer)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = FertilizerForm(instance=fertilizer)
    return render(request, 'main/add_fertilizer.html', {'form': form})

def delete_p_profile(request, pk):
    get_object_or_404(P_profile, pk=pk).delete()
    return redirect('profile_pp')

def add_p_profile(request):
    if request.method == 'POST':
        form = P_profileForm(request.POST)
        if form.is_valid():
            p_profile = form.save(commit=False)
            p_profile.user = request.user
            p_profile.save()
            return redirect('profile_pp')
    else:
        form = P_profileForm()
    return render(request, 'main/add_p_profile.html', {'form': form})

def edit_p_profile(request, pk):
    p_profile = get_object_or_404(P_profile, pk=pk)
    if request.method == 'POST':
        form = P_profileForm(request.POST, instance=p_profile)
        if form.is_valid():
            form.save()
            return redirect('profile_pp')
    else:
        form = P_profileForm(instance=p_profile)
    return render(request, 'main/add_p_profile.html', {'form': form})

def calc(request):
    if request.user.is_authenticated:
        fertilizers = Fertilizer.objects.filter(Q(user=request.user) | Q(is_public=True))
        p_profiles = P_profile.objects.filter(Q(user=request.user) | Q(is_public=True))
    else:
        fertilizers = Fertilizer.objects.filter(Q(is_public=True))
        p_profiles = P_profile.objects.filter(Q(is_public=True))
    names = []
    answer = []
    er=""
    profile=[]
    el_names=[]
    selected_fertilizers = []
    selected_profile = p_profiles[0]
    if request.method == 'POST':
        selected_fertilizers = Fertilizer.objects.filter(id__in=request.POST.getlist('fertilizers'))
        selected_profile = get_object_or_404(P_profile, id=request.POST.get('p_profile'))
        water = float(request.POST.get('water_l'))

        if selected_fertilizers:
            f = []
            profile = list(vars(selected_profile).values())[6:]
            el_names = list(vars(selected_profile).keys())[6:]
            for i in range(8):
                profile[i+8] = profile[i+8] * 0.001

            for fertilize in selected_fertilizers:
                new_f = vars(fertilize)
                new_f['p2o5']=new_f['p2o5'] * 0.436
                new_f['k2o']=new_f['k2o'] * 0.83
                new_f['cao']=new_f['cao'] * 0.715
                new_f['mgo']=new_f['mgo'] * 0.603
                names.append(list(new_f.values())[4])
                f.append(list(new_f.values())[5:])

            def mix(doses, f):
                result = [0]*16
                for i in range(len(doses)):
                    for k in range(16):
                        result[k]+=(doses[i]*f[i][k])/100
                return result

            def func(doses, f, profile):
                fault = 0.05
                res = mix(doses, f)
                penalty = 0
                covered = 0
                for i in range(len(profile)):
                    if profile[i] > 0:
                        if abs(res[i]-profile[i])/profile[i] <= fault:
                            covered += 1
                        elif res[i] > profile[i]:
                            penalty += ((res[i] - profile[i]) ** 2) * (0.1+(((i//8))*0.9))
                        else:
                            penalty += (profile[i] - res[i]) * (0.1+(((i//8))*0.9))
                return penalty - (covered*(1/16)*penalty)
            
            start_doses = [0] * len(selected_fertilizers)
            bounds = [(0, None) for _ in range(len(selected_fertilizers))]

            answer = minimize(func, start_doses, args=(f, profile), bounds=bounds, method='L-BFGS-B').x 

            for k in range(16):
                for i in range(len(selected_fertilizers)):
                    profile[k] -= (f[i][k]*answer[i])/100
            profile = list(map(lambda x: round(x * water), profile))
            answer = list(map(lambda x: round(x * water), answer))

        else:
            er = "Выберите хотя бы 1 удобрение"

        
    return render(request, 'main/calc.html', {'fertilizers': fertilizers, 'p_profiles': p_profiles, 'answer': dict(zip(names, answer)), 'er': er, 'res': dict(zip(el_names, profile)), 'selected_fertilizers': [x.id for x in selected_fertilizers], 'selected_profile': selected_profile.id})

def calc_p_profile(request):
    start_profile = {
      "N": 100,
      "P": 20,
      "K": 50,
      "Ca": 60,
      "Mg": 25,
      "S": 15
    }
    return render(request, "main/calc_p_profile.html", {"macros": start_profile})

def upload_p_profiles(request):
    er = None
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        d = {'Старт': 'start', 'Вегетация': 'veg', 'Поздняя вегетация': 'late_veg', 'Плодоношение': 'fruiting'}
        if form.is_valid():
            file = request.FILES['file']
            tab = openpyxl.load_workbook(file).active
            for row in tab.iter_rows(min_row=2, values_only=True):
                if (type(row[0]) != str) or not(row[1] in d) or not(all(isinstance(x, (int, float)) for x in row[2:18])):
                    er = 'Некорректные данные в файле'
                    form = UploadFileForm()
                    return render(request, 'main/upload.html', {'form': form, 'error': er, 'cancel': 'profile_pp'})
            for row in tab.iter_rows(min_row=2, values_only=True):
                P_profile.objects.create(user=request.user, name=row[0],
                                        growth_stage=d.get(row[1]),
                                        no3=row[2], 
                                        nh4=row[3], 
                                        p=row[4], 
                                        k=row[5], 
                                        ca=row[6], 
                                        mg=row[7], 
                                        s=row[8], 
                                        cl=row[9], 
                                        fe=row[10], 
                                        mn=row[11], 
                                        b=row[12],
                                        zn=row[13], 
                                        cu=row[14], 
                                        mo=row[15], 
                                        co=row[16], 
                                        si=row[17])
            return redirect('profile_pp')
    else:

main/templates/main/add_fertilizer.html
{% extends "main/index.html" %}

{% block title %}Добавление удобрения{% endblock %}
{% block content %}
<div class="container py-5">
    <h2 class="text-success">Новое удобрение</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'profile' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

main/templates/main/add_p_profile.html
{% extends "main/index.html" %}

{% block title %}Добавление профиля питания{% endblock %}
{% block content %}
<div class="container py-5">
    <h2 class="text-success">Новый профиль питания</h2>
    
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Сохранить</button>
        <a href="{% url 'profile_pp' %}" class="btn btn-secondary">Отмена</a>
    </form>
</div>
{% endblock %}

main/templates/main/calc.html
{% extends "main/index.html" %}

{% block title %}Калькулятор удобрений{% endblock %}
{% block content %} 
<div class="container">
    <div class="card shadow-sm mx-auto" style="max-width: 700px;">
        <div class="card-body">
            <h1 class="card-title text-center mb-4">Выбор профиля питания и удобрений</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-4">
                    <hr class="my-4">
                    <h5 class="text-center mb-3">Профиль питания</h5>

                    <div class="mb-4">
                        <label for="growthStageSelect" class="form-label fw-bold">Выберите стадию роста:</label>
                        <select class="form-select" id="growthStageSelect">
                            <option value="">Все стадии</option>
                            <option value="start">Старт</option>
                            <option value="veg">Вегетация</option>
                            <option value="late_veg">Поздняя вегетация</option>
                            <option value="fruiting">Плодоношение</option>
                        </select>
                    </div>

                    <label for="profileSearch" class="form-label fw-bold">Поиск растения:</label>
                    <input type="text" class="form-control mb-3" id="profileSearch" placeholder="Начните вводить название растения...">

                    <div class="mb-4">
                        <label for="ProfileSelect" class="form-label fw-bold">Выберите растение:</label>
                        <select class="form-select" id="ProfileSelect" name="p_profile">
                            {% for profile in p_profiles %}
                            <option value="{{ profile.id }}" {% if selected_profile == profile.id %}selected{% endif %}
                                data-growth-stage="{{ profile.growth_stage }}"
                                title="{% if profile.no3 %}NO₃: {{ profile.no3 }} мг/л; {% endif %}{% if profile.nh4 %}NH₄: {{ profile.nh4 }} мг/л; {% endif %}{% if profile.p %}P: {{ profile.p }} мг/л; {% endif %}{% if profile.k %}K: {{ profile.k }} мг/л; {% endif %}{% if profile.ca %}Ca: {{ profile.ca }} мг/л; {% endif %}{% if profile.mg %}Mg: {{ profile.mg }} мг/л; {% endif %}{% if profile.s %}S: {{ profile.s }} мг/л; {% endif %}{% if profile.cl %}Cl: {{ profile.cl }} мг/л; {% endif %}{% if profile.fe %}Fe: {{ profile.fe }} мкг/л; {% endif %}{% if profile.mn %}Mn: {{ profile.mn }} мкг/л; {% endif %}{% if profile.b %}B: {{ profile.b }} мкг/л; {% endif %}{% if profile.zn %}Zn: {{ profile.zn }} мкг/л; {% endif %}{% if profile.cu %}Cu: {{ profile.cu }} мкг/л; {% endif %}{% if profile.mo %}Mo: {{ profile.mo }} мкг/л; {% endif %}{% if profile.co %}Co: {{ profile.co }} мкг/л; {% endif %}{% if profile.si %}Si: {{ profile.si }} мкг/л{% endif %}">
                            {{ profile.name }}({{ profile.get_growth_stage_display }})
                        </option>
                            {% endfor %}
                        </select>
                    </div>



                    <hr>

                    <h5 class="text-center mb-3">Удобрения</h5>

                    <label for="fertilizerSearch" class="form-label fw-bold">Поиск удобрения:</label>
                    <input type="text" class="form-control mb-3" id="fertilizerSearch" placeholder="Начните вводить название удобрения...">

                    <label class="form-label fw-bold">Выберите удобрения:</label>
                    <div style="max-height: 400px; overflow-y: auto; padding-left: 3px;">
                        {% for fertilizer in fertilizers %}
                        <div class="form-check">
                            <input class="form-check-input" style="border: solid;" type="checkbox" name="fertilizers" value="{{ fertilizer.id }}" id="fert{{ fertilizer.id }}" {% if fertilizer.id in selected_fertilizers %}checked{% endif %}>
                            <label class="form-check-label" for="fert{{ fertilizer.id }}">
                                {{ fertilizer.name }}<br>
                                <small class="text-muted">(
                                    {% if fertilizer.no3 %} NO<sub>3</sub>: {{ fertilizer.no3 }}%{% endif %}
                                    {% if fertilizer.nh4 %} NH<sub>4</sub>: {{ fertilizer.nh4 }}%{% endif %}
                                    {% if fertilizer.p2o5 %} P<sub>2</sub>O<sub>5</sub>: {{ fertilizer.p2o5 }}%{% endif %}
                                    {% if fertilizer.k2o %} K<sub>2</sub>O: {{ fertilizer.k2o }}%{% endif %}
                                    {% if fertilizer.cao %} CaO: {{ fertilizer.cao }}%{% endif %}
                                    {% if fertilizer.mgo %} MgO: {{ fertilizer.mgo }}%{% endif %}
                                    {% if fertilizer.s %} S: {{ fertilizer.s }}%{% endif %}
                                    {% if fertilizer.cl %} Cl: {{ fertilizer.cl }}%{% endif %}
                                    {% if fertilizer.fe %} Fe: {{ fertilizer.fe }}%{% endif %}
                                    {% if fertilizer.mn %} Mn: {{ fertilizer.mn }}%{% endif %}
                                    {% if fertilizer.b %} B: {{ fertilizer.b }}%{% endif %}
                                    {% if fertilizer.zn %} Zn: {{ fertilizer.zn }}%{% endif %}
                                    {% if fertilizer.cu %} Cu: {{ fertilizer.cu }}%{% endif %}
                                    {% if fertilizer.mo %} Mo: {{ fertilizer.mo }}%{% endif %}
                                    {% if fertilizer.co %} Co: {{ fertilizer.co }}%{% endif %}
                                    {% if fertilizer.si %} Si: {{ fertilizer.si }}%{% endif %}
                                )</small>
                            </label>
                        </div>
                        {% endfor %}
                    </div>
                </div>

                <hr>

                <div class="mb-4 d-flex align-items-center">
                    <label for="waterL" class="form-label fw-bold me-2" style="white-space: nowrap;">Количество воды в литрах:</label>
                    <input type="number" min = "0" step="0.1" class="form-control" id="waterL" name="water_l" value="1", required>
                </div>

                <button type="submit" class="btn btn-success w-100">Рассчитать</button>
            </form>
        </div>
    </div>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
<script>
    document.getElementById('fertilizerSearch').addEventListener('input', function () {
        const query = this.value.toLowerCase();
        document.querySelectorAll('.form-check').forEach(check => {
            const label = check.textContent.toLowerCase();
            check.style.display = label.includes(query) ? 'block' : 'none';
        });
    });

    document.addEventListener('DOMContentLoaded', function () {
        const searchInput = document.getElementById('profileSearch');
        const select = document.getElementById('ProfileSelect');
        const growthStage = document.getElementById('growthStageSelect');

        function filter() {
            const query = searchInput.value.toLowerCase();
            const stage = growthStage.value;

            const filtered = Array.from(select.options).filter(x => {
                const textMatch = x.text.toLowerCase().includes(query);
                const stageMatch = !stage || x.dataset.growthStage === stage;
                x.style.display = (textMatch && stageMatch) ? 'block' : 'none';
            });
        }

        searchInput.addEventListener('input', filter);
        growthStage.addEventListener('change', filter);
    });
</script>

<hr>

<div class="row">
    <div class="col-md-6">
        <ul class="list-group small">
            <li class="list-group-item active">Дозировки выбранных удобрений:</li>
            {% for key, value in answer.items %}
                <li class="list-group-item d-flex justify-content-between px-2 py-1">
                    <span>{{ key }}</span>
                    <span class='value'>{{ value }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-md-6">
        <ul class="list-group small">
            <li class="list-group-item active bg-success border-success">Недостающие элементы:</li>
            {% for key, value in res.items %}
                {% if value != 0 %}
                <li class="list-group-item d-flex justify-content-between px-2 py-1">
                    <span>{{ key }}</span>
                    <span class='value'>{{ value }}</span>
                </li>{% endif %}
            {% endfor %}
        </ul>
    </div>
</div>

<script>
    document.querySelectorAll('.value').forEach(x => {
        let num = parseFloat(x.textContent);
        if (num > 1000) {
            x.textContent = (num/1000) + ' г';
        } else {
            x.textContent = num + ' мг';
        }
    })
</script>

{% if er %}
    <div class="alert alert-warning mt-2 py-1 px-2 small" role="alert">
        {{ er }}
    </div>
{% endif %}

{% endblock %}

main/templates/main/login.html
{% extends "main/index.html" %}

{% block title %}Login{% endblock %}
{% block content %}{% if error %}
<div class="alert alert-danger w-75 mx-auto mt-3" role="alert">
    {{ error }}
</div>
{% endif %}
<form method="POST">
    {% csrf_token %}
    <div class="mb-3">
        <label for="usrnm" class="form-label">Логин:</label>
        <input name="username" type="text" class="form-control" id="usrnm" placeholder="Введите логин">
    </div>
    <div class="mb-3">
        <label for="psw" class="form-label">Пароль:</label>
        <input name="password" type="password" class="form-control" id="psw" placeholder="Введите пароль">
    </div>
    <button type="submit" class="btn btn-primary px-4">Войти</button>
</form>{% endblock %}

main/templates/main/profile_pp.html
{% extends "main/index.html" %}

{% block title %}Профиль с удобрениями{% endblock %}
{% block content %}
<div class="container py-3">
    <div class="card mb-3">
        <div class="card-body text-center">
            <h1 class="card-title">Профиль пользователя: {{ user.username }}</h1>
        </div>
    </div>

    <div class="container text-center mt-4">
        <div class="row g-3">
            <div class="col-md-6">
                <a href="{% url 'profile' %}" class="btn btn-success w-100 py-3">Удобрения</a>
            </div>
            <div class="col-md-6">
                <a href="{% url 'profile_pp' %}" class="btn btn-primary w-100 py-3">Профили питания</a>
            </div>
        </div>
    </div>
    

    <div class="container py-3">
        <h2 class="text-success mb-4">Ваши профили питания растений:</h2>
    
        {% for p_profile in p_profiles %}
        <div class="card mb-4 shadow-sm p-3 rounded">
            <div class="card-body">
                <h3 class="card-title text-center">{{ p_profile.name }}({{ p_profile.get_growth_stage_display }})</h3>
                <hr>
                <div class="table-responsive">
                    <table class="table table-bordered text-center">
                        <thead class="table-success">
                            <tr>
                                <th>NO<sub>3</sub>, мг/л</th>
                                <th>NH<sub>4</sub>, мг/л</th>
                                <th>P, мг/л</th>
                                <th>K, мг/л</th>
                                <th>Ca, мг/л</th>
                                <th>Mg, мг/л</th>
                                <th>S, мг/л</th>
                                <th>Cl, мг/л</th>
                                <th>Fe, мкг/л</th>
                                <th>Mn, мкг/л</th>
                                <th>B, мкг/л</th>
                                <th>Zn, мкг/л</th>
                                <th>Cu, мкг/л</th>
                                <th>Mo, мкг/л</th>
                                <th>Co, мкг/л</th>
                                <th>Si, мкг/л</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ p_profile.no3 }}</td>
                                <td>{{ p_profile.nh4 }}</td>
                                <td>{{ p_profile.p }}</td>
                                <td>{{ p_profile.k }}</td>
                                <td>{{ p_profile.ca }}</td>
                                <td>{{ p_profile.mg }}</td>
                                <td>{{ p_profile.s }}</td>
                                <td>{{ p_profile.cl }}</td>
                                <td>{{ p_profile.fe }}</td>
                                <td>{{ p_profile.mn }}</td>
                                <td>{{ p_profile.b }}</td>
                                <td>{{ p_profile.zn }}</td>
                                <td>{{ p_profile.cu }}</td>
                                <td>{{ p_profile.mo }}</td>
                                <td>{{ p_profile.co }}</td>
                                <td>{{ p_profile.si }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="d-flex gap-2 justify-content-center">
                <a href="{% url 'edit_p_profile' p_profile.id %}" class="btn btn-primary">Редактировать</a>
                <a href="{% url 'delete_p_profile' p_profile.id %}" class="btn btn-danger">Удалить</a>
            </div>
        </div>
        {% empty %}
            <p class="text-muted text-center">У вас пока нет профилей питания</p>
        {% endfor %}
        <a href="{% url 'add_p_profile' %}" class="btn btn-success mt-3">Добавить профиль питания</a><br>
        <a href="{% url 'upload_p_profiles' %}" class="btn btn-primary mt-3">Загрузить профили питания из файла</a>
        <a href="{% url 'download_p_profiles' %}" class="btn btn-secondary mt-3">Сохранить ваши профили питания в файл</a>
    </div>
{% endblock %}